/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.mdp2223.emanuelevesprini.robot.utilities;

import it.unicam.cs.mdp2223.emanuelevesprini.robot.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
